apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: karsajobs-ui
    tier: frontend