apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: karsajobs-ui
        tier: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: symrizals/karsajobs-ui:latest
        ports:
        - containerPort: 8000
        env:
        - name: VUE_APP_API_URL
          value: http://karsajobs-service:8080
