apiVersion: apps/v1
kind: Deployment
metadata:
  # Nama Deployment untuk backend karsajobs
  name: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  # Jumlah replica Pod yang dijalankan
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
      - name: karsajobs
        # Image yang digunakan dari Docker Hub
        image: ghcr.io/symrizals/karsajobs:latest
        ports:
        - containerPort: 8080
        env:
        # Port aplikasi backend berjalan
        - name: APP_PORT
          value: "8080"
        # Host MongoDB menggunakan nama Headless Service
        - name: MONGO_HOST
          value: mongo-service
        # Username MongoDB diambil dari Secret
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        # Password MongoDB diambil dari Secret
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
