apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
      - name: karsajobs
        image: symrizals/karsajobs:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password