apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # base64 dari "adminpassword"
  mongo-root-password: YWRtaW5wYXNzd29yZA==
  # base64 dari "karsajobs"
  mongo-username: a2Fyc2Fqb2Jz
  # base64 dari "karsajobspassword"
  mongo-password: a2Fyc2Fqb2JzcGFzc3dvcmQ=
