apiVersion: v1
kind: Secret
metadata:
  # Nama Secret yang akan direferensikan oleh StatefulSet
  name: mongo-secret
# Opaque adalah tipe default untuk menyimpan data arbitrary
type: Opaque
data:
  # Username root MongoDB dalam format base64 ("admin")
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Password root MongoDB dalam format base64 ("supersecretpassword")
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
