apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
          name: mongo
        env:
        # Username diambil dari file Secret
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        # Password diambil dari file Secret
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        # Mount Persistent Volume untuk data MongoDB
        - name: mongo-persistent-storage
          mountPath: /data/db
        # Mount ConfigMap untuk konfigurasi MongoDB
        - name: mongo-config
          mountPath: /config
        # Mount Secret untuk credentials MongoDB
        - name: mongo-credentials
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: mongo-config
        configMap:
          name: mongo-config
      - name: mongo-credentials
        secret:
          secretName: mongo-secret
