name: CI Pipeline - Karsajobs UI Frontend

on:
  push:
    branches:
      - karsajobs-ui
  pull_request:
    branches:
      - karsajobs-ui

jobs:
  # Job 1: Lint Dockerfile menggunakan hadolint
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  # Job 2: Build dan push image ke GitHub Container Registry
  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    needs: lint-dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login ke GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u symrizals --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/symrizals/karsajobs-ui:latest .

      - name: Push Docker image
        run: docker push ghcr.io/symrizals/karsajobs-ui:latest
